# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: pass12345
      POSTGRES_USER: food_user
      POSTGRES_DB: FoodDB

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379