# Generated by Django 5.0.6 on 2024-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poct')),
                ('subject', models.CharField(max_length=150, verbose_name='Movzu')),
                ('meesage', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
