# Generated by Django 5.0.6 on 2024-06-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='meesage',
            new_name='message',
        ),
    ]
