# Generated by Django 5.0.6 on 2024-06-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipe',
            options={'ordering': ['-created_at']},
        ),
    ]
