# Generated by Django 5.0.6 on 2024-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_receipe_author_category_receipe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='receipe',
            name='tags',
            field=models.ManyToManyField(related_name='receipes', to='stories.tag'),
        ),
    ]
