# Generated by Django 5.0.6 on 2024-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_recipecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
