# Generated by Django 5.0.6 on 2024-06-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_tag_receipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
