# Generated by Django 5.0.6 on 2024-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_cover'),
        ),
    ]
