# Generated by Django 5.0.6 on 2024-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_receipe_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='category_cover'),
        ),
    ]
